version: '3.7'
services:

  mysql01:
    image: mysql:5.7
    volumes:
      - .:/data
    command: mysqld --datadir=/tmp/data --event-scheduler=ON
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fleet
      MYSQL_USER: fleet
      MYSQL_PASSWORD: fleet
    ports:
      - "3306:3306"

  redis01:
    image: redis:3.2.4
    ports:
      - "6379:6379"

  fleet01:
    image: kolide/fleet:latest
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    environment:
      KOLIDE_MYSQL_ADDRESS: mysql01:3306
      KOLIDE_MYSQL_DATABASE: fleet
      KOLIDE_MYSQL_USERNAME: fleet
      KOLIDE_MYSQL_PASSWORD: fleet
      KOLIDE_REDIS_ADDRESS: redis01:6379
      KOLIDE_SERVER_ADDRESS: 0.0.0.0:17010
      KOLIDE_AUTH_JWT_KEY: FdxvIZiar2EQXE3azq30An1YpwcSQSwk
      KOLIDE_SERVER_CERT: /fleet/osquery/fleet.crt
      KOLIDE_SERVER_KEY: /fleet/osquery/fleet.key
      KOLIDE_LOGGING_JSON: 'true'
      KOLIDE_OSQUERY_STATUS_LOG_PLUGIN: filesystem
      KOLIDE_FILESYSTEM_STATUS_LOG_FILE: /logs/osqueryd.status.log
      KOLIDE_OSQUERY_RESULT_LOG_PLUGIN: filesystem
      KOLIDE_FILESYSTEM_RESULT_LOG_FILE: /logs/osqueryd.results.log
    depends_on:
      - mysql01
      - redis01
    volumes:
      - .:/fleet/
      - fleet_logs:/logs
    ports:
      - "17010:17010"

volumes:
  data01:
    driver: local
  fleet_logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/fleet_logs
